name: Build Plugin

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Build Solution
      run: msbuild OverwatchDumpFix.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: OverwatchDumpFix-Plugin
        path: |
          x64/Release/*.dp64
          x64/Release/*.dll
